import './globals.css'
import { Inter, Oxygen } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const oxy = Oxygen({ subsets: ['latin'], weight: ["300", "400", "700"] })

export const metadata = {
  title: 'Cliff Sanchez (@techbycliff)',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={oxy.style}>{children}</body>
    </html>
  )
}
